version: '3.6'

services:
  my-mongodb:
    image: 'mongo'
    container_name: 'my-mongodb'
    environment:
      - MONGO_INITDB_DATABASE=messaging
      - MONGO_INITDB_ROOT_USERNAME=iamaldren
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'
    expose:
      - '27017'
    networks:
      - messaging_api
  messaging-api-1.0.0:
    image: 'messaging-api-1.0.0'
    container_name: 'messaging-api-1.0.0'
    depends_on:
      - my-mongodb
    ports:
      - '8080:8080'
    environment:
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://iamaldren:secret@my-mongodb:27017/messaging
      - MONGODB_STATUS_HOST=my-mongodb
      - MONGODB_STATUS_PORT=27017
    networks:
      - messaging_api

networks:
  messaging_api: