version: '3.6'

services:
  my-mongodb:
    image: 'iamaldrew/messaging-mongo'
    container_name: 'my-mongodb'
    ports:
      - '27017:27017'
    expose:
      - '27017'
    networks:
      - messaging_api
  messaging-api-1.0.0:
    image: 'iamaldrew/messaging-api'
    container_name: 'messaging-api'
    depends_on:
      - my-mongodb
    ports:
      - '8080:8080'
    environment:
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://iamaldren:secret@my-mongodb:27017/messaging
      - MONGODB_STATUS_HOST=my-mongodb
      - MONGODB_STATUS_PORT=27017
    networks:
      - messaging_api

networks:
  messaging_api: